version: "3.8"

services:
  # BlobFuse setup service (runs once to configure host)
  blobfuse-setup:
    image: ubuntu:22.04
    container_name: blobfuse-setup
    privileged: true
    volumes:
      - /:/host
      - ./setup-blobfuse.sh:/setup-blobfuse.sh:ro
    environment:
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
    command: >
      bash -c "
        echo 'Setting up BlobFuse on host system...' &&
        chroot /host /bin/bash -c 'cd /tmp && cp /setup-blobfuse.sh . && chmod +x setup-blobfuse.sh && ./setup-blobfuse.sh' &&
        echo 'BlobFuse setup completed'
      "
    restart: "no"
    profiles:
      - setup

  # Database service
  nextcloud-db:
    image: mariadb:11.4
    container_name: nextcloud-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 384M
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-buffer-pool-size=256M --innodb-log-file-size=64M --innodb-flush-method=O_DIRECT --query-cache-size=32M --tmp-table-size=64M --max-heap-table-size=64M
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      - nextcloud-network

  # Redis cache service
  nextcloud-redis:
    image: redis:8.2.1-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 96mb --maxmemory-policy allkeys-lru --save 300 10
    volumes:
      - nextcloud_redis_data:/data
    networks:
      - nextcloud-network

  # Nextcloud application
  nextcloud-app:
    image: nextcloud:30.0-apache
    container_name: nextcloud-app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    ports:
      - "8080:80" # Expose on port 8080 for Caddy to proxy
    volumes:
      - nextcloud_app_data:/var/www/html
      - nextcloud_data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
      - ./nextcloud-custom.ini:/usr/local/etc/php/conf.d/nextcloud-custom.ini:ro
      - /mnt/blobfuse:/mnt/azure-blob:rw
      - ./nextcloud-entrypoint.sh:/nextcloud-entrypoint.sh:ro
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://${NEXTCLOUD_DOMAIN}
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=172.16.0.0/12 192.168.0.0/16 10.0.0.0/8 127.0.0.1
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=1G
      - APACHE_BODY_LIMIT=1073741824
    entrypoint: ["/nextcloud-entrypoint.sh"]
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-network
    healthcheck:
      test: ["CMD-SHELL", "test -d /mnt/azure-blob || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Cron job service for background tasks
  nextcloud-cron:
    image: nextcloud:30.0-apache
    container_name: nextcloud-cron
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - nextcloud_app_data:/var/www/html
      - nextcloud_data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/blobfuse:/mnt/azure-blob:rw
    entrypoint: /cron.sh
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-network


networks:
  nextcloud-network:
    driver: bridge

volumes:
  nextcloud_db_data:
    driver: local
  nextcloud_redis_data:
    driver: local
  nextcloud_app_data:
    driver: local
  nextcloud_data:
    driver: local