version: "3.8"

services:
  # Database service
  nextcloud-db:
    image: mariadb:11.4
    container_name: nextcloud-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 150M
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-buffer-pool-size=128M --innodb-log-file-size=32M --innodb-flush-method=O_DIRECT --query-cache-size=16M --tmp-table-size=32M --max-heap-table-size=32M
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      - nextcloud-network
      - npm_default # Connect to existing Nginx Proxy Manager network

  # Redis cache service
  nextcloud-redis:
    image: redis:7.4-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 80M
        reservations:
          memory: 64M
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 64mb --maxmemory-policy allkeys-lru --save 300 10
    volumes:
      - nextcloud_redis_data:/data
    networks:
      - nextcloud-network

  # Nextcloud application
  nextcloud-app:
    image: nextcloud:29-apache
    container_name: nextcloud-app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 300M
    expose:
      - "80" # Only expose internally, Nginx Proxy Manager handles external access
    volumes:
      - nextcloud_app_data:/var/www/html
      - nextcloud_data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
      - ./nextcloud-custom.ini:/usr/local/etc/php/conf.d/nextcloud-custom.ini:ro
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://${NEXTCLOUD_DOMAIN}
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=172.16.0.0/12 192.168.0.0/16 10.0.0.0/8
      - PHP_MEMORY_LIMIT=256M
      - PHP_UPLOAD_LIMIT=1G
      - APACHE_BODY_LIMIT=1073741824
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-network
      - npm_default # Connect to existing Nginx Proxy Manager network

  # Cron job service for background tasks
  nextcloud-cron:
    image: nextcloud:29-apache
    container_name: nextcloud-cron
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 100M
    volumes:
      - nextcloud_app_data:/var/www/html
      - nextcloud_data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /cron.sh
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-network

networks:
  nextcloud-network:
    driver: bridge
  npm_default:
    external: true # Use existing Nginx Proxy Manager network

volumes:
  nextcloud_db_data:
    driver: local
  nextcloud_redis_data:
    driver: local
  nextcloud_app_data:
    driver: local
  nextcloud_data:
    driver: local
